// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClAh1ltEZyS13fqLkktYdpFYgBDvx35Wk',
    appId: '1:333949308882:web:15e7b01d1441060b09020b',
    messagingSenderId: '333949308882',
    projectId: 'eecommerce-c229f',
    authDomain: 'eecommerce-c229f.firebaseapp.com',
    databaseURL: 'https://eecommerce-c229f-default-rtdb.firebaseio.com',
    storageBucket: 'eecommerce-c229f.appspot.com',
    measurementId: 'G-L1YMJJY5FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXjMMWrXRmWcuxAYP8oc_qQlecwml8AWw',
    appId: '1:333949308882:android:9d94791090b81e9209020b',
    messagingSenderId: '333949308882',
    projectId: 'eecommerce-c229f',
    databaseURL: 'https://eecommerce-c229f-default-rtdb.firebaseio.com',
    storageBucket: 'eecommerce-c229f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT_6B7GlT_JJj1MeMatK39-BwCkgYS_AA',
    appId: '1:333949308882:ios:1351d97a130d23de09020b',
    messagingSenderId: '333949308882',
    projectId: 'eecommerce-c229f',
    databaseURL: 'https://eecommerce-c229f-default-rtdb.firebaseio.com',
    storageBucket: 'eecommerce-c229f.appspot.com',
    iosClientId: '333949308882-smq7thcpgiodg4l9sb03bfr07j9cphrd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT_6B7GlT_JJj1MeMatK39-BwCkgYS_AA',
    appId: '1:333949308882:ios:cb3f82179ce7004d09020b',
    messagingSenderId: '333949308882',
    projectId: 'eecommerce-c229f',
    databaseURL: 'https://eecommerce-c229f-default-rtdb.firebaseio.com',
    storageBucket: 'eecommerce-c229f.appspot.com',
    iosClientId: '333949308882-nc8ejsdp12gh2r8n41iki61n91hqsthe.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
